version: 2
updates:
  - package-ecosystem: yarn
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 99
    reviewers:
      - KevinBacas
    assignees:
      - KevinBacas
    versioning-strategy: increase
